# Site settings
title: enriquein's blog
email: enriquein@gmail.com
description: "My blog. Or my attempt at maintaining one."
baseurl: ""
url: "http://enriquein.github.io"

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- More -->"
